### ISSUE TITLE
issue in syncfusion/boldbi container

### ISSUE THREAD

**Issue by rajesh054** [boldbi/boldbi-docker#13]
After 1st time doing "docker-compose up -d" , the container runs fine. But if we stop and start the same container of syncfusion/boldbi then it throws error  "Restarting (1) 38 seconds ago".
Url logs screen shot and along with container ls screenshot is attached please help what to do?
https://ibb.co/MhZc6W5
https://ibb.co/XSks3xQ

to tackle this issue i am currently deleting the stopped container and rerunning docker compose to start new container as the data is mounted to local disk.
But this is not the right way , need help if there is any issue with the docker image of syncfusion/boldbi
solution as early as possible will be very much helpful

**Comment by SivanesanSyncfusion** [comment]
Concern addressed

**Comment by SivanesanSyncfusion** [comment]
concern addressed
